version: '2'
services:
  emailrelay-in:
    build: Dockerfiles/emailrelay-in
    ports:
      - "127.0.0.1:25:25"
    expose:
      - 25
    hostname: emailrelay-in
    volumes:
      - ERSpoolVolume:/var/spool/emailrelay
    depends_on:
      - emailrelay-out
    networks:
      - ernet

  emailrelay-out:
    image: dcagatay/emailrelay
    ports:
      - "${ER_OUT_PORTNO}:${ER_OUT_PORTNO}"
    environment:
      PORT: ${ER_OUT_PORTNO}
    networks:
      - ernet
    extra_hosts:
      - "${EXT_MAIL_SERVER}:${EXT_MAIL_SERVER_IP}"
    volumes:
      - ERDataVolume:/var/spool/emailrelay
    command:
      - --forward-on-disconnect
      - --forward-to 
      - ${EXT_MAIL_SERVER}:${EXT_MAIL_SERVER_PORT} 
      - --forward
      - --client-tls
      - --tls-config=tlsv1.2
      - --filter
      - net:emailrelay-parser:1235 
      - --filter-timeout=70
 
  emailrelay-parser:
    build: Dockerfiles/parser
    ports:
      - "127.0.0.1:1235:1235"
    expose:
      - 5000
    hostname: parser
    networks:
      - ernet
    volumes:
      - ImagesVolume:/images
      - ./dlp_model:/dlp_model
    volumes_from:
      - emailrelay-out
 
  flask:
    build: Dockerfiles/flask
    ports:
      - "127.0.0.1:5000:5000"
    hostname: flask
    networks:
      - ernet
    volumes:
      - ./mails:/mails
  
  images-web:
    build: Dockerfiles/images
    ports:
      - "127.0.0.1:80:80"
    hostname: images
    networks:
      - ernet
    volumes_from:
      - emailrelay-parser

  tika-parser:
    build: Dockerfiles/tika
    ports:
      - "127.0.0.1:9998:9998"
    hostname: tika
    networks:
      - ernet
volumes:
  ERSpoolVolume:
  ERDataVolume:
  ImagesVolume:
networks:
  ernet:
